### ISSUE TITLE
没有看见弹幕，现在不能使用了吗？

### ISSUE THREAD

**Issue by doraemonkeys** [Chorder/danmuju#1]
Chrome 版本 131.0.6778.205

![image](https://github.com/user-attachments/assets/0708df1e-8046-4886-81b7-ba40b45ab288)
![image](https://github.com/user-attachments/assets/9a6cb7b0-9ac4-4490-82a5-4905ecd1b32c)
![image](https://github.com/user-attachments/assets/9ddc8a91-3551-493e-afd2-265d2cd165b8)

**Comment by Chorder** [comment]
不是的，因为用的人还太少了。你可以自己发送几条，就可以看见弹幕飘过了。

**Comment by doraemonkeys** [comment]
报错 Error fetching missiles: TypeError: Failed to fetch

api请求返回
{"missiles":[]}

**Comment by Chorder** [comment]
> 报错 Error fetching missiles: TypeError: Failed to fetch
> 
> api请求返回 {"missiles":[]}

api请求返回{"missiles":[]}就是当前页面没有弹幕

**Comment by doraemonkeys** [comment]
> > 报错 Error fetching missiles: TypeError: Failed to fetch
> > api请求返回 {"missiles":[]}
> 
> api请求返回{"missiles":[]}就是当前页面没有弹幕

不是的，在百度首页上面，一个都没有

**Comment by Chorder** [comment]
> > > 报错 Error fetching missiles: TypeError: Failed to fetch
> > > api请求返回 {"missiles":[]}
> > 
> > 
> > api请求返回{"missiles":[]}就是当前页面没有弹幕
> 
> 不是的，在百度首页上面，一个都没有

客户端请求服务端弹幕是基于时间戳的。在localStorage中有一个cursor变量，记录的是上次请求弹幕的时间戳。
服务端会根据这个时间戳，取这个时间戳之后的弹幕。
如果你希望看到这个页面有史以来的所有弹幕，把cursor变量删除，或者改为0，即可。

**Comment by doraemonkeys** [comment]
> > > > 报错 Error fetching missiles: TypeError: Failed to fetch
> > > > api请求返回 {"missiles":[]}
> > > 
> > > 
> > > api请求返回{"missiles":[]}就是当前页面没有弹幕
> > 
> > 
> > 不是的，在百度首页上面，一个都没有
> 
> 客户端请求服务端弹幕是基于时间戳的。在localStorage中有一个cursor变量，记录的是上次请求弹幕的时间戳。 服务端会根据这个时间戳，取这个时间戳之后的弹幕。 如果你希望看到这个页面有史以来的所有弹幕，把cursor变量删除，或者改为0，即可。

错过就看不到了的话，感觉没有意义啊

**Comment by Chorder** [comment]
> > > > > 报错 Error fetching missiles: TypeError: Failed to fetch
> > > > > api请求返回 {"missiles":[]}
> > > > 
> > > > 
> > > > api请求返回{"missiles":[]}就是当前页面没有弹幕
> > > 
> > > 
> > > 不是的，在百度首页上面，一个都没有
> > 
> > 
> > 客户端请求服务端弹幕是基于时间戳的。在localStorage中有一个cursor变量，记录的是上次请求弹幕的时间戳。 服务端会根据这个时间戳，取这个时间戳之后的弹幕。 如果你希望看到这个页面有史以来的所有弹幕，把cursor变量删除，或者改为0，即可。
> 
> 错过就看不到了的话，感觉没有意义啊

嗯，需要再优化一下。
